// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ProjectWebApi.Models
{
    public partial class Events
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("eventName")]
        public string EventName { get; set; }
        [Column("eventDescription")]
        public string EventDescription { get; set; }
    }
}