// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ProjectWebApi.Models
{
    public partial class Notes
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        public string NoteTitle { get; set; }
        public string NoteSubtitle { get; set; }
    }
}